### ISSUE TITLE
How is pcl/pcl file created?

### ISSUE THREAD

**Issue by phy25** [scottlx/Wheelchair-Arm-Control#5]
Hi, I am wondering how is [pcl/pcl](https://github.com/scottlx/Wheelchair-Arm-Control/blob/master/pcl/pcl) file created? Is it compiled with catkin_make from correspondence_grouping.cpp?

If that is the case, I think the following two lines should be modified from `ork` to `pcl`. Also this pcl executable file should never be put inside Git (maybe with a `.gitignore`?); it should be generated by the user with the catkin_make setup command.

https://github.com/scottlx/Wheelchair-Arm-Control/blob/96b62bff482b034f0aeb5c6884bbff984d55af50/pcl/CMakeLists.txt#L11-L12

**Comment by manymuch** [comment]
Thanks for your advice, that was a mistake. I mannully change the executable file name from ork to pcl. I will fix that. Thanks!
