### ISSUE TITLE
More comments are needed in your codes.

### ISSUE THREAD

**Issue by ZeyuKeithFu** [scottlx/Wheelchair-Arm-Control#6]
Very impressive project! 

For someone who has no experience on robot operating system, like me, the demo images are really helpful. I can clearly see what arm structure is like, and  I can basically understand what is the functions of each part in the system. And also,  I can implement the functions by following the "How to run" part. For every step, there are some result images after the descriptions. This is really important so that I can check if the system can work well when implementing. 

After knowing  the functions and how to basically use them, next thing I want to do is to check how the functions are built, so I reviewed the codes. In every file, I can see one part for configuration and one part for launching the robotic arm. When I am checking the ```.launch``` and ```.config``` files,  it is really hard for me to understand because I have never working on ROS. Also, there is no description words in the beginning of the file, so I can only guess the function of the script by file names, especially in ```arm_moveit_config/launch/``` folder with so many files. 

My suggestion is to add some comments in your code, at least a description words at the beginning, this will be really important to help others understand your code. When I see a code, I prefer, and tend to read them block by block, but not reading them as a whole. Imagine the situation and you will find it is really a big problem to solve. I believe many people have the same habit to read codes block by block, just like when they write the codes. The comments are what divide the code into blocks and make the code more readable.

At last, I really appreciate your work. You have done really a lot on this. I believe it will be a great project and hope to see the complete version of it!

**Comment by scottlx** [comment]
Thanks for your review. The reason some code has no comments is that they are generated by pacakges or they are just some config file. I will classify them in the readme next time to notice which one is written by ourselves and which is not.
I really appreciate your review!
